config:
  kafka-brokers: ${KAFKA_BROKERS:localhost:9092}
  application-id: ${APPLICATION_ID:account-bookings-kafka-streams}
  schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
  topic-accounts: ${KAFKA_TOPIC_ACCOUNTS:event_core_banking_accounts}
  topic-bookings: ${KAFKA_TOPIC_BOOKINGS:event_core_banking_bookings}
  output-topic-name: ${KAFKA_TOPIC_ACCOUNT_BOOKINGS:event_core_banking_account_bookings}
  output-topic-partitions: ${KAFKA_TOPIC_ACCOUNT_BOOKINGS_PARTITIONS:1}
  output-topic-replicas: ${KAFKA_TOPIC_ACCOUNT_BOOKINGS_REPLICAS:1}

spring:
  kafka:
    properties:
      bootstrap.servers: ${config.kafka-brokers}
      # set to true if you don't want to register the schemas up front.
      auto.register.schemas: true
      schema.registry.url: ${config.schema-registry-url}

    streams:
      replication-factor: 1
      application-id: ${config.application-id}
