version: "3.9"
services:
  datagen:
    image: "datagen:latest"
    build:
      context: ../modules/datagen
    environment:
      KAFKA_TOPIC_NAME: "event_customer_entity"
      KAFKA_BOOTSTRAP_SERVERS: "broker:29092"
      KAFKA_SCHEMA_REGISTRY_URL: "schema-registry:8081"
      CORE_BANKING_DB_HOST: "postgresql-core-banking"
      CORE_BANKING_DB_PORT: "5432"
      CORE_BANKING_DB_USER: "user"
      CORE_BANKING_DB_PASSWORD: "password"
      CORE_BANKING_DB_NAME: "core-banking"
      CONTACT_CENTER_DB_URI: "mongodb://mongodb-contact-center:27017"
      CONTACT_CENTER_DB_USER: "user"
      CONTACT_CENTER_DB_PASSWORD: "password"
      CONTACT_CENTER_DB_NAME: "contact-center"
    volumes:
      - "../schemas/customer-key.avsc:/schemas/customer-key.avsc"
      - "../schemas/customer-value.avsc:/schemas/customer-value.avsc"
      - "./wait-for-it.sh:/wait-for-it.sh"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - >
        /wait-for-it.sh schema-registry:8081 -s -t 120 --
        /wait-for-it.sh broker:9092 -s -t 60 --
        /go/bin/app -key-schema-file=/schemas/customer-key.avsc -value-schema-file=/schemas/customer-value.avsc
    #command:
    #  - "-key-schema-file=/schemas/customer-key.avsc"
    #  - "-value-schema-file=/schemas/customer-value.avsc"
    depends_on:
      - mongodb-contact-center
      - postgresql-core-banking
      - broker

  postgresql-core-banking:
    image: "bitnami/postgresql:14.1.0"
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: "user"
      POSTGRESQL_PASSWORD: "password"
      # https://github.com/bitnami/bitnami-docker-postgresql/blob/master/12/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L353
      POSTGRESQL_REPLICATION_USER: "replication-user"
      POSTGRESQL_REPLICATION_PASSWORD: "password"
      POSTGRESQL_DATABASE: "core-banking"
      POSTGRESQL_WAL_LEVEL: "logical"
    volumes:
      - "../schemas/core-banking.ddl:/docker-entrypoint-initdb.d/core-banking.sql"

  # https://github.com/bitnami/bitnami-docker-mongodb#setting-up-replication
  mongodb-contact-center:
    image: "bitnami/mongodb:4.4.10-debian-10-r44"
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_USER: "admin"
      MONGODB_ROOT_PASSWORD: "admin"
      MONGODB_USERNAME: "user"
      MONGODB_PASSWORD: "password"
      MONGODB_DATABASE: "contact-center"
      MONGODB_SYSTEM_LOG_VERBOSITY: "1"
      MONGODB_ADVERTISED_HOSTNAME: "mongodb-contact-center"
      #MONGODB_REPLICA_SET_NAME: "contact-center"
      MONGODB_REPLICA_SET_MODE: "primary"
      MONGODB_REPLICA_SET_KEY: "contactCenterRs1"

  mongodb-customer-single-view:
    image: "bitnami/mongodb:4.4.10-debian-10-r44"
    ports:
      - "27018:27017"
    environment:
      MONGODB_ROOT_USER: "admin"
      MONGODB_ROOT_PASSWORD: "admin"
      MONGODB_USERNAME: "user"
      MONGODB_PASSWORD: "password"
      MONGODB_DATABASE: "customer-single-view"
