CREATE OR REPLACE STREAM EVENT_CUSTOMER_COUNTRY AS
SELECT
    CUSTOMER_ID,
    NAME,
    SURNAME,
    EMAIL,
    FILTER(ADDRESSES, x => x->DEFAULT = TRUE)[1]->COUNTRY AS COUNTRY,
    FILTER(TELEPHONES, x => x->PRIMARY = TRUE)[1]->NUMBER AS TELEPHONE
FROM EVENT_CUSTOMER_ENTITY
EMIT CHANGES;

SELECT COUNTRY, COUNT(*) "COUNT"
FROM EVENT_CUSTOMER_COUNTRY
GROUP BY COUNTRY
EMIT CHANGES;