@startyaml
<style>
yamlDiagram {
  BackGroundColor white
  LineThickness 1
  LineColor black
}
</style>

customer_id: String
name: String
surname: String
email: String
telephones:
    - number: String
      primary: Boolean
addresses:
    - street: String
      number: String
      city: String
      country: String
      zip_code: String
      default: Boolean

@endyaml