@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

<style>
classDiagram {
  BackGroundColor white
  LineThickness 1
  LineColor black
}
</style>

entity "ACCOUNTS" as accounts {
* account_id : NUMBER <<generated>>
---
* customer_id : VARCHAR(50)
iban : VARCHAR(35)
balance : NUMBER(20,3)
creation_date : TIMESTAMP(3)
cancellation_date : TIMESTAMP(3)
status : VARCHAR(10)
}

entity "BOOKINGS" as bookings {
* booking_id : NUMBER <<generated>>
---
* amount : NUMBER(20,3)
description : VARCHAR(250)
booking_date : TIMESTAMP(3)
value_date : TIMESTAMP(3)
fee : NUMBER(20,3)
taxes : NUMBER(20,3)
}

accounts ||..o{ bookings
accounts -r[hidden]-> bookings

@enduml
