@startyaml
<style>
yamlDiagram {
  BackGroundColor white
  LineThickness 1
  LineColor black
}
</style>

_id: String
case_id: String
customer_id: String
title: String
creation_timestamp: Timestamp
communications:
    - communication_id: String
      timestamp: Timestamp
      type: [phone, email]
      text: String
      notes: String

@endyaml